global using MediatR;
global using Microsoft.Extensions.Logging;
global using Microsoft.EntityFrameworkCore;
global using FluentValidation;
global using Security;
global using Kernel;
global using ContentService.Core.AggregateModel.ContentAggregate;
global using ContentService.Core.AggregateModel.JsonPropertyModelAggregate;
global using ContentService.Core.AggregateModel.JsonSchemaModelAggregate;