@startuml

package DigitalAssetService {


	class DigitalAsset {
		-Guid DigitalAssetId
		-string Name
		-byte[] Bytes
		-string ContentType
		-float Height
		-float Width	
	}
}


package CatalogService {

	class CatalogService.Product {
		-Guid ProductId
		-Guid? BrandId
		-Guid? ProductCategoryId
		-string Name
		-ICollection<ProductImage> ProductImages
		-string Description
		-ProductCategory ProductCategory
		-Brand Brand
		-int Price
		-ProductType Type		
	}
	
	class Brand {
		-Guid BrandId
		-string Name
		-string Description
	}
	
	class ProductType {
		-Guid ProductTypeId
		-string Name
		-string Description
	}
	
	class ProductCategory {
		-Guid ProductCategoryId
		-string Name
		-string Description
	}	
	
	class ProductImage {
		-Guid ProductImageId
		-string Name
		-string Url
	}
}



package ContentService {
	class Content {
		-Guid ContentId
		-string Name
		-Newtonsoft.Json.Linq.JObject Json
		-string Slug
	}
}

package CustomerService {
	class CustomerService.Customer {
		-Guid CustomerId
		-string FirstName
		-string LastName
		-string Email
		-string PhoneNumber
	}
}


package DashboardService {

	class DashboardService.User {
		-Guid UserId
		-string Username
		-List<Dashboard> Dashboards
	}

	class Dashboard {
		-Guid DashboardId
		-string Name
		-Guid? UserId
		-List<DashboardCard> DashboardCards
	}
	
	class DashboardCard {
		-Guid DashboardCardId
		-Guid DashboardId
		-Guid CardId
		-Guid CardLayoutId
		-Dashboard Dashboard
		-Card Card
		-CardLayout CardLayout
		-JObject Options
	}
	
	class Card {
		-Guid CardId
		-string Name
		-string Description
	}
	
	class CardLayout {
		-Guid CardLayoutId
		-string Name
		-string Description
	}
}


package IdentityService {

	class IdentityService.User { 
		-Guid UserId
		-string Username
		-string Password
		-byte[] Salt
		-List<Role> Roles
	}

	class Role {
		-Guid RoleId
		-string Name
		-List<User> Users
		-List<Privilege> Privileges
	}

	class Privilege
	{
		-Guid PrivilegeId
		-Guid RoleId
		-Security.AccessRight AccessRight
		-string Aggregate
	}

	IdentityService.User *--* Role
	Role --* Privilege
}

package OtpService {
	class OtpService {
		-Guid UserId
		-string Username
		-byte[] Salt
	}

}

package OrderService {
	class Tax {
		-double Rate
		-TaxRateType Type
		-DateTime Effective
	}
	
	class Order {
		-Guid OrderId
		-float Cost
		-OrderStatus Status
		-List<OrderLineItem> LineItems		
	}
	
	class OrderLineItem {
	
	}
	
	enum OrderStatus {
		New
		Paid
	}

}


package InventoryService {
	class InventoryItem {
	        -Guid InventoryItemId
        	-Guid ProductId
        	-Guid? WarehouseId
		-Guid? BinId
		-int Quantity
		-DateTime Modified
		-Warehouse Warehouse
		-Product Product
		-Bin Bin
	}
	
	class InventoryService.Product {
		-Guid ProductId
		-string Name
		-string Description
	}
	
	class Bin {
		-Guid BinId
		-string Name
		-string Description
	}
	
	class Warehouse {
		-Guid WarehouseId
		-string Name
		-string Description	
	}
}

package PaymentService {

}

package ThemeService {
	class Theme {
		-Guid ThemeId
		-string Name
		-JObject CssCustomProperties
	}
}


@enduml
