@startuml

package BasketService {

}


package CatalogService {

	class Product {
		+Guid ProductId
		+Guid? BrandId
		+Guid? ProductCategoryId
		+string Name
		+ICollection<ProductImage> ProductImages
		+string Description
		+ProductCategory ProductCategory
		+Brand Brand
		+int Price
		+ProductType Type		
	}
	
	class Brand {
		+Guid BrandId
		+string Name
		+string Description
	}
	
	class ProductType {
		+Guid ProductTypeId
		+string Name
		+string Description
	}
	
	class ProductCategory {
		+Guid ProductCategoryId
		+string Name
		+string Description
	}	
	
	class ProductImage {
		+Guid ProductImageId
		+string Name
		+string Url
	}
}



package ContentService {
	class Content {
		+Guid ContentId
		+string Name
		+Newtonsoft.Json.Linq.JObject Json
		+string Slug
	}
}

package CustomerService {
	class Customer {
		+Guid CustomerId
	}
}


package DashboardService {

	class DashboardService.User {
		+Guid UserId
		+string Username
	}

	class Dashboard {
		+Guid DashboardId
		+string Name
		+Guid? UserId
	}
	
	class DashboardCard {
		+Guid DashboardCardId
		+Guid DashboardId
		+JObject Options
	}
	
	class Card {
		+Guid CardId
		+string Name
		+string Description
	}
	
	class CardLayout {
		+Guid CardLayoutId
		+string Name
	}	
}


package IdentityService {

	class User { 
		+Guid UserId
		+string Username
		+string Password
		+byte[] Salt
		+List<Role> Roles
	}

	class Role {
		+Guid RoleId
		+string Name
		+List<User> Users
		+List<Priviledge> Priviledges
	}

	class Priviledge
	{
		+Guid PrivilegeId
		+Guid RoleId
		+Security.AccessRight AccessRight
		+string Aggregate
	}

	IdentityService.User *--* Role
	Role --* Priviledge
}

package OtpService {

}

package CustomerService {

}


package InventoryService {

}

package PaymentService {

}

package ThemeService {
	class Theme {
		+Guid ThemeId
		+string Name
	}
}


@enduml
